name: upload_app
description: App Flutter com Firebase Authentication e Storage usando Clean Architecture

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5

  # Utilitários
  file_picker: ^10.1.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0

  # Material
  cupertino_icons: ^1.0.6
  open_filex: ^4.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  bloc_test: ^10.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
